# Generated by Django 6.0.2 on 2026-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_num_reviews_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Member'},
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
