# Generated by Django 6.0.2 on 2026-03-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_member_options_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wishlist_books',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='myapp.book'),
        ),
    ]
